export interface ProductFormData {
  id?: string;
  name: string;
  description?: string;
  shortDescription?: string;
  modelNumber?: string;
  tagline?: string;
  productLine?: string;
  productSeries?: string;
  phase?: "SINGLE_PHASE" | "THREE_PHASE" | "NOT_APPLICABLE" | "";
  hp?: string;
  boxType?: string;
  meterType?: string;
  startCapacitor?: string;
  runCapacitor?: string;
  capacitor?: string;
  maxLoad?: string;
  mcbRelayOlp?: string;
  warranty?: string;
  voltage?: string;
  ampRating?: string;
  suitableFor?: string;
  protectionFeatures?: string;
  useCases?: string;
  manualUrl?: string;
  videoUrl?: string;
  featuredVideoUrl?: string;
  seoTitle?: string;
  seoDescription?: string;
  isActive: boolean;
  isPublished: boolean;
  isCatalogVisible: boolean;
  enquiryEnabled: boolean;
  sortOrder?: number;
  categoryId: string;
  isNew: boolean;
  isTrending: boolean;
  isBestSeller: boolean;
  isFeatured: boolean;
  variants: {
    id: string;
    sku: string;
    price: number;
    priceVisible?: boolean;
    images: File[];
    stock: number;
    stockVisible?: boolean;
    lowStockThreshold?: number;
    barcode?: string;
    warehouseLocation?: string;
    hp?: string;
    hpMin?: number;
    hpMax?: number;
    phase?: "SINGLE_PHASE" | "THREE_PHASE" | "NOT_APPLICABLE" | "";
    variantType?: string;
    maxLoadAmps?: number;
    boxType?: string;
    bodyType?: string;
    meterType?: string;
    meterDisplayType?: "ANALOG" | "DIGITAL" | "NOT_APPLICABLE" | "";
    meterSize?: string;
    startCapacitor?: string;
    runCapacitor?: string;
    mcbRelayOlp?: string;
    warranty?: string;
    protectionFeatures?: string;
    installationInfo?: string;
    manualUrl?: string;
    videoUrl?: string;
    isActive?: boolean;
    sortOrder?: number;
    attributes: { attributeId: string; valueId: string }[];
  }[];
}
